config/routes.rb
Rails.application.routes.draw do
  resources :businesses

  resources :categories

  root 'static_pages#home'

end

app/models/business.rb
class Business < ActiveRecord::Base
	mount_uploader :picture, PictureUploader
	belongs_to :category

	def avatar=(obj)
	    super(obj)
    	# Put your callbacks here, e.g.
    	self.moderated = false  
  	end

  	def open(daytime)
  		if daytime
  			"Open"
  		else 
  			"Closed"
  		end
  	end
end

app/models/category.rb
class Category < ActiveRecord::Base
 	mount_uploader :picture, PictureUploader
	has_many :businesses

	def avatar=(obj)
    super(obj)
    # Put your callbacks here, e.g.
    self.moderated = false  
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :set_business, only: [:show, :edit, :update, :destroy]

  # GET /businesses
  # GET /businesses.json
  def index
    # @businesses = Business.all
    @category = Category.find(params[:category_id]) if params[:category_id]

    if params[:morning]
      @businesses = Category.find_by_name(@category.name).businesses.where(:morning => true)
    elsif params[:lunch]
      @businesses = Category.find_by_name(@category.name).businesses.where(:lunch => true)
    elsif params[:afternoon]
      @businesses = Category.find_by_name(@category.name).businesses.where(:afternoon => true)
    elsif params[:night]
      @businesses = Category.find_by_name(@category.name).businesses.where(:night => true)
    else
      params[:category_id].present? ?
        @businesses = Category.find_by_name(@category.name).businesses :
        @businesses = Business.all
    end
  end

  # GET /businesses/1
  # GET /businesses/1.json
  def show
  end

  # GET /businesses/new
  def new
    @business = Business.new
  end

  # GET /businesses/1/edit
  def edit
  end

  # POST /businesses
  # POST /businesses.json
  def create
    @business = Business.new(business_params)

    respond_to do |format|
      if @business.save
        format.html { redirect_to @business, notice: 'Business was successfully created.' }
        format.json { render :show, status: :created, location: @business }
      else
        format.html { render :new }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /businesses/1
  # PATCH/PUT /businesses/1.json
  def update
    respond_to do |format|
      if @business.update(business_params)
        format.html { redirect_to @business, notice: 'Business was successfully updated.' }
        format.json { render :show, status: :ok, location: @business }
      else
        format.html { render :edit }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /businesses/1
  # DELETE /businesses/1.json
  def destroy
    @business.destroy
    respond_to do |format|
      format.html { redirect_to businesses_url, notice: 'Business was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business
      @business = Business.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_params
      params.require(:business).permit(:category_id, :name, :description, :picture, :morning, :lunch, :afternoon, :night)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :picture)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @business = Business.new
    @categories = Category.all.collect {|c| [ c.name, c.id ] }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/businesses/_form.html.erb
<%= form_for @business, :html => {:multipart => true} do |f| %>
  <% if @business.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@business.errors.count, "error") %> prohibited this business from being saved:</h2>

      <ul>
      <% @business.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category %><br>
    <%= f.select("category_id", Category.all.collect {|c| [ c.name, c.id ] }) %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="field">
    <%= f.label :morning %><br>
    <%= f.check_box :morning %>
  </div>
  <div class="field">
    <%= f.label :lunch %><br>
    <%= f.check_box :lunch %>
  </div>
  <div class="field">
    <%= f.label :afternoon %><br>
    <%= f.check_box :afternoon %>
  </div>
  <div class="field">
    <%= f.label :night %><br>
    <%= f.check_box :night %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/businesses/edit.html.erb
<h1>Editing business</h1>

<%= render 'form' %>

<%= link_to 'Show', @business %> |
<%= link_to 'Back', businesses_path %>

app/views/businesses/index.html.erb
<h1>List of Businesses</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Name</th>
      <th>Description</th>
      <th>Image</th>
      <th>Morning</th>
      <th>Lunch</th>
      <th>Afternoon</th>
      <th>Night</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
   
    <%= link_to 'New Business', new_business_path %>

    <% @businesses.each do |business| %>
      
      <tr>
        <td><%= business.category.name unless business.category.nil? %></td>
        <td><%= business.name %></td>
        <td><%= link_to "Maps", business.description, target: '_blank' %></td>
        <td><%= image_tag(business.picture_url, :width => 120) if business.picture.present? %></td>
        <td><%= business.open(business.morning) %></td>
        <td><%= business.open(business.lunch) %></td>
        <td><%= business.open(business.afternoon) %></td>
        <td><%= business.open(business.night) %></td>
        <td><%= link_to 'Show', business %></td>
        <td><%= link_to 'Edit', edit_business_path(business) %></td>
        <td><%= link_to 'Delete', business, method: :delete, data: { confirm: 'OOOOH! Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/businesses/new.html.erb
<h1>New business</h1>

<%= render 'form' %>

<%= link_to 'Back', businesses_path %>

app/views/businesses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @business.category.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @business.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= link_to @business.description, @business.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @business.picture, style: "width:300px" %>
</p>

<p>
  <strong>Morning:</strong>
  <%= @business.morning %>
</p>

<p>
  <strong>Lunch:</strong>
  <%= @business.lunch %>
</p>

<p>
  <strong>Afternoon:</strong>
  <%= @business.afternoon %>
</p>

<p>
  <strong>Night:</strong>
  <%= @business.night %>
</p>

<%= link_to 'Edit', edit_business_path(@business) %> |
<%= link_to 'Back', businesses_path %>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= image_tag(category.picture_url, :width => 80) if category.picture.present? %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag @category.picture, style: "width:300px" %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Isitopen</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	  <div class="container">
	    <div class="navbar-header">
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="/">Home</a>
	    </div>
	          
	      </ul>
	    </div>
	  </div>
	</nav>

    <%= yield %>

</body>
</html>

app/views/static_pages/home.html.erb
<div id="home-bg">	
	<h1>Is it Open? </h1>
	<h2>Check it here! </h2>

	<%= form_tag('/businesses', method: 'get') do %>
	  <div class="field">
	    <%= label_tag :category %><br>
	    <%= select_tag "category_id", options_for_select(Category.all.collect { |c| [ c.name, c.id ] }) %>
	  </div>

	  <div class="field">
	    <%= label_tag :morning %><br>
	    <%= check_box_tag :morning %>
	  </div>
	  <div class="field">
	    <%= label_tag :lunch %><br>
	    <%= check_box_tag :lunch %>
	  </div>
	  <div class="field">
	    <%= label_tag :afternoon %><br>
	    <%= check_box_tag :afternoon %>
	  </div>
	  <div class="field">
	    <%= label_tag :night %><br>
	    <%= check_box_tag :night %>
	  </div>

	  <%= submit_tag "Search" %>
	 <% end %>
</div>